#!/usr/bin/env python3
"""Assemble collector/static/src/*.js (ordre alphabétique) en collector/static/dashboard.js.

  python tools/build_dashboard.py           # génère dashboard.js
  python tools/build_dashboard.py --check   # échoue si dashboard.js n'est pas à jour (CI)

Le résultat est un seul script classique (pas de modules ES) : les handlers inline
`onclick="..."` du HTML continuent de fonctionner, et les déclarations `function` sont
hoistées sur l'ensemble du fichier, donc l'ordre des modules n'a pas d'impact sur les appels.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "collector" / "static" / "src"
OUT = ROOT / "collector" / "static" / "dashboard.js"
HEADER = (
    "/* AUTO-GENERATED by tools/build_dashboard.py. DO NOT EDIT HERE: "
    "modify collector/static/src/*.js, then run `python tools/build_dashboard.py`. */\n"
)


def build() -> str:
    files = sorted(SRC.glob("*.js"))
    if not files:
        raise SystemExit(f"Aucun module trouvé dans {SRC}")
    parts = [
        f"/* ---- {f.name} ---- */\n" + f.read_text(encoding="utf-8").rstrip("\n") + "\n"
        for f in files
    ]
    return HEADER + "\n".join(parts)


def main() -> int:
    out = build()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != out:
            print("dashboard.js n'est pas à jour : lance `python tools/build_dashboard.py`")
            return 1
        print("dashboard.js à jour")
        return 0
    OUT.write_text(out, encoding="utf-8", newline="\n")
    print(f"{OUT.relative_to(ROOT)} <- {len(list(SRC.glob('*.js')))} modules, {len(out.splitlines())} lignes")
    return 0


if __name__ == "__main__":
    sys.exit(main())